# Generated by Django 4.1.1 on 2022-09-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest1', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest2', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest3', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest4', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest5', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest6', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest7', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest8', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest9', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest10', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest11', models.CharField(blank=True, max_length=200, null=True)),
                ('manifest12', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
